#!/bin/bash
python bbox.py /home/anagpal/nba_pose_data/outputN.57_dunk_636_771_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.5_dunk_1663_1798_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.5_three-pointer_1212_1347_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.5_three-pointer_1814_1949_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.5_three-pointer_2440_2575_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.5_three-pointer_2505_2640_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.5_three-pointer_2669_2804_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.5_three-pointer_412_547_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.5_three-pointer_844_979_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.64_dunk_131_266_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.66_dunk_1174_1309_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.69_dunk_121_256_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.6_dunk_1062_1197_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.6_three-pointer_1210_1345_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.6_three-pointer_1695_1830_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.6_three-pointer_1863_1998_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.6_three-pointer_533_668_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.71_dunk_1921_2056_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.71_dunk_627_762_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.71_dunk_861_996_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.71_three-pointer_1121_1256_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.71_three-pointer_1513_1648_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.74_dunk_2657_2792_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.75_dunk_1082_1217_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.75_dunk_1633_1768_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.75_dunk_928_1063_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.76_dunk_1473_1608_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.76_dunk_1946_2081_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.76_dunk_335_470_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.78_dunk_1746_1881_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.78_dunk_426_561_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.78_dunk_909_1044_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.79_dunk_150_285_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.7_dunk_143_278_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.80_dunk_663_798_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.82_dunk_2740_2875_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.82_dunk_2904_3039_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.8_three-pointer_1673_1808_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.8_three-pointer_2456_2591_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.8_three-pointer_2807_2942_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.8_three-pointer_3014_3149_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.8_three-pointer_318_453_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.9_dunk_1380_1515_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.9_three-pointer_1043_1178_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.9_three-pointer_1214_1349_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.9_three-pointer_1780_1915_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.9_three-pointer_2088_2223_original.mp4 --use_cuda false
python bbox.py /home/anagpal/nba_pose_data/outputN.9_three-pointer_2305_2440_original.mp4 --use_cuda false
